### ISSUE TITLE
We're sorry something went wrong

### ISSUE THREAD

**Issue by jhriv** [ucsdlib/hyrax-demo#2]
After closing the port to the world, the `production.log` is much cleaner.

When hitting the app at the front end this line appears in the logs:

`F, [2018-03-16T11:43:13.427450 #1886] FATAL -- : [cce19870-8563-4a2d-8d9a-2fcebd411878] RuntimeError (No roles were found for the production environment in /opt/horton/releases/20180313214440Z/config/role_map.yml):`

**Comment by jhriv** [comment]
[production-log-single-hit.txt](https://github.com/ucsdlib/hyrax-demo/files/1820646/production-log-single-hit.txt)

**Comment by mcritchlow** [comment]
So I think the issue is that the app is being run in `production` mode, and we have no content in the `production` section of the `config/role_map.yml` file. As a stopgap for testing, I think it would be worth trying to replace the existing section w/ something like:

````
production:
  admin:
    - jhriv@ucsd.edu
    - gamontoya@ucsd.edu
````

We might need to also add/run `rake hyrax:default_admin_set:create hyrax:workflow:load` somewhere in the install playbook at some point. Note I'm referencing this from the [Development Guide](https://github.com/samvera/hyrax/wiki/Hyrax-Development-Guide#work-with-test-app-in-the-browser)

**Comment by mcritchlow** [comment]
also if you want to verify the admin role is being applied, you'll need to create an account with that email address in the app. But if you can get that far, then I think we'll have already made progress

**Comment by jhriv** [comment]
Manually adding the admin: stanza with the two users worked.
